CLASSPATH = .
OPTS = -g
run: Mainxkcdpwgen.class
	java -cp $(CLASSPATH) Mainxkcdpwgen

Mainxkcdpwgen.class: Mainxkcdpwgen.java
	javac $(OPTS) -cp $(CLASSPATH) Mainxkcdpwgen.java

clean:
	rm -f Mainxkcdpwgen.class
